#!/bin/bash
set -euo pipefail

app_user="${APP_USER:?APP_USER must be set}"
app_password="${APP_USER_PASSWORD:?APP_USER_PASSWORD must be set}"

sql_identifier="$(printf '%s' "$app_user" | tr '[:lower:]' '[:upper:]')"

sqlplus -s / as sysdba <<EOF
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER=FREEPDB1;
ALTER USER ${app_user} QUOTA UNLIMITED ON USERS;
GRANT EXECUTE ON MDSYS.SDO_GEOMETRY TO ${sql_identifier};
GRANT EXECUTE ON MDSYS.SDO_POINT_TYPE TO ${sql_identifier};
GRANT EXECUTE ON MDSYS.SDO_DIM_ARRAY TO ${sql_identifier};
GRANT EXECUTE ON MDSYS.SDO_DIM_ELEMENT TO ${sql_identifier};

CONNECT ${app_user}/${app_password}@//localhost/FREEPDB1

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE work_orders CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE field_sites CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  DELETE FROM USER_SDO_GEOM_METADATA WHERE table_name = 'FIELD_SITES' AND column_name = 'LOCATION';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(100) NOT NULL,
  email_address VARCHAR2(255) NOT NULL UNIQUE,
  province_code CHAR(2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE field_sites (
  site_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  site_name VARCHAR2(100) NOT NULL,
  site_type VARCHAR2(40) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  location MDSYS.SDO_GEOMETRY NOT NULL,
  location_geojson VARCHAR2(512) NOT NULL,
  installed_on DATE NOT NULL,
  CONSTRAINT chk_field_sites_location_geojson
    CHECK (location_geojson IS JSON),
  CONSTRAINT fk_field_sites_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE work_orders (
  work_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  site_id NUMBER NOT NULL,
  summary VARCHAR2(200) NOT NULL,
  priority VARCHAR2(20) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  requested_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP,
  CONSTRAINT fk_work_orders_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_work_orders_site
    FOREIGN KEY (site_id) REFERENCES field_sites(site_id)
);

INSERT INTO USER_SDO_GEOM_METADATA (table_name, column_name, diminfo, srid)
VALUES (
  'FIELD_SITES',
  'LOCATION',
  MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.0005),
    MDSYS.SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.0005)
  ),
  4326
);

INSERT INTO customers (customer_id, customer_name, email_address, province_code, created_at)
VALUES (1, 'North Ridge Forestry', 'ops@northridge.example', 'BC', TIMESTAMP '2026-01-05 08:30:00');

INSERT INTO customers (customer_id, customer_name, email_address, province_code, created_at)
VALUES (2, 'Harbor Utilities', 'dispatch@harbor.example', 'BC', TIMESTAMP '2026-01-08 09:45:00');

INSERT INTO customers (customer_id, customer_name, email_address, province_code, created_at)
VALUES (3, 'Interior Survey Labs', 'gis@interior.example', 'BC', TIMESTAMP '2026-01-12 14:15:00');

INSERT INTO field_sites (site_id, customer_id, site_name, site_type, status, location, location_geojson, installed_on)
VALUES (
  1,
  1,
  'Vancouver Control Point',
  'CONTROL_POINT',
  'ACTIVE',
  MDSYS.SDO_GEOMETRY(
    2001,
    4326,
    MDSYS.SDO_POINT_TYPE(-123.1207, 49.2827, NULL),
    NULL,
    NULL
  ),
  '{"type":"Point","coordinates":[-123.1207,49.2827]}',
  DATE '2025-06-01'
);

INSERT INTO field_sites (site_id, customer_id, site_name, site_type, status, location, location_geojson, installed_on)
VALUES (
  2,
  2,
  'Victoria Harbor Sensor',
  'SENSOR',
  'ACTIVE',
  MDSYS.SDO_GEOMETRY(
    2001,
    4326,
    MDSYS.SDO_POINT_TYPE(-123.3656, 48.4284, NULL),
    NULL,
    NULL
  ),
  '{"type":"Point","coordinates":[-123.3656,48.4284]}',
  DATE '2025-07-15'
);

INSERT INTO field_sites (site_id, customer_id, site_name, site_type, status, location, location_geojson, installed_on)
VALUES (
  3,
  3,
  'Kamloops Survey Marker',
  'SURVEY_MARKER',
  'MAINTENANCE',
  MDSYS.SDO_GEOMETRY(
    2001,
    4326,
    MDSYS.SDO_POINT_TYPE(-120.3273, 50.6745, NULL),
    NULL,
    NULL
  ),
  '{"type":"Point","coordinates":[-120.3273,50.6745]}',
  DATE '2025-08-22'
);

INSERT INTO work_orders (work_order_id, customer_id, site_id, summary, priority, status, requested_at, completed_at)
VALUES (
  1,
  1,
  1,
  'Quarterly calibration of Vancouver control point',
  'HIGH',
  'OPEN',
  TIMESTAMP '2026-03-01 07:45:00',
  NULL
);

INSERT INTO work_orders (work_order_id, customer_id, site_id, summary, priority, status, requested_at, completed_at)
VALUES (
  2,
  2,
  2,
  'Battery replacement for harbor sensor',
  'MEDIUM',
  'COMPLETED',
  TIMESTAMP '2026-02-14 11:20:00',
  TIMESTAMP '2026-02-16 16:35:00'
);

INSERT INTO work_orders (work_order_id, customer_id, site_id, summary, priority, status, requested_at, completed_at)
VALUES (
  3,
  3,
  3,
  'Inspect survey marker footing after frost event',
  'HIGH',
  'IN_PROGRESS',
  TIMESTAMP '2026-03-10 09:00:00',
  NULL
);

INSERT INTO work_orders (work_order_id, customer_id, site_id, summary, priority, status, requested_at, completed_at)
VALUES (
  4,
  1,
  1,
  'Validate coordinate drift threshold report',
  'LOW',
  'OPEN',
  TIMESTAMP '2026-03-18 13:10:00',
  NULL
);

COMMIT;
EXIT;
EOF